---
- name: "Set {{ option }} to {{ value }} in {{ file }}.conf"
  ini_file:
    path: "/etc/sysctl.d/{{ file }}.conf"
    section: null
    option: "{{ option }}"
    value: "{{ value }}"
    mode: '0644'
  notify: Reload sysctl
